protocol: Zyzzyva
phases:
  Request: 
    quorum: 1
    next_state: SpeculativeExecute
    actions:
      - verifySignature:
          public_key: "../keys/${client_id}_public.pem"
      - "handleClientRequestAsLeader"
  SpeculativeExecute:
    quorum: 1
    next_state: Request
    actions:
      - "storeMessage"
      - "speculativeComplete"
  Commit:
    quorum: 1
    next_state: Request
    actions:
      - "commitCertificate"

  ViewChange:
    quorum: 2f+1
    next_state: NewView
    actions:
      - "zyzzyvaViewChange"

  NewView:
    quorum: 1
    next_state: Request
    actions:
      - "zyzzyvaHandleNewView"

  QueryBalances:
    quorum: 1
    next_state: Request
    actions:
      - "queryBalances"

