entities:
  #  turning off the leader to test Byzantine behavior
  # - id: 1
  #   role: Leader
  #   byzantine: true
  #   peers: [1, 2, 3, 4, 5, 6, 7]
  - id: 2
    role: Replica
    byzantine: false
    peers: [1, 2, 3, 4, 5, 6, 7]
  - id: 3
    role: Replica
    byzantine: false
    peers: [1, 2, 3, 4, 5, 6, 7]
  - id: 4
    role: Replica
    byzantine: false
    peers: [1, 2, 3, 4, 5, 6, 7]
  - id: 5
    role: Replica
    byzantine: false
    peers: [1, 2, 3, 4, 5, 6, 7]
  - id: 6
    role: Replica
    byzantine: false
    peers: [1, 2, 3, 4, 5, 6, 7]
  - id: 7
    role: Replica
    byzantine: false
    peers: [1, 2, 3, 4, 5, 6, 7]